### ISSUE TITLE
Breaks bootstrap 5 theme plugins

### ISSUE THREAD

**Issue by xtreme2020** [yajra/laravel-datatables-vite#3]
Hi,
Everytime i load datatables , it's breaks my currents Jquery plugins, if i remove it everything back to normal, can you make no conflict jquery version, to prevent theses problems.

Thanks

**Comment by yajra** [comment]
Can you provide snippets to reproduce the issue? 

As I recall, `document.ready` should be replaced with `document.addEventListener('DOMContentLoaded', function () {` and the inline scripts to be loaded as type module.

**Comment by yajra** [comment]
Found an issue with how the bootstrap was imported. Kindly try again on v0.5.2. Thanks!

**Comment by xtreme2020** [comment]
> Found an issue with how the bootstrap was imported. Kindly try again on v0.5.2. Thanks!

Thanks for your fast response, i will let you know when i test it again

**Comment by ameerElsherif** [comment]
Issue still exists on v0.5.2
Loading datatables breaks bootstrap's dropdowns for me.

**Comment by taufiqridha** [comment]
> Found an issue with how the bootstrap was imported. Kindly try again on v0.5.2. Thanks!

I'm also having same issue. it breaks bootstrap's dropdown

**Comment by taufiqridha** [comment]
> Issue still exists on v0.5.2 Loading datatables breaks bootstrap's dropdowns for me.

I solved my problem by not importing bootstrap on my resource/app.js . Check on this code, they are also importing bootstrap with datatable . By removing our bootstrap It prevent  bootstrap imported twice and stop working
