### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'defaults') 

### ISSUE THREAD

**Issue by Abubuckersidhiq** [yajra/laravel-datatables-vite#9]
laravel-datatables-vite.js?v=9c8e9b71:21674 Uncaught TypeError: Cannot read properties of undefined (reading 'defaults') at laravel-datatables-vite.js?v=9c8e9b71:21674:55// facing this issue in latest version of this package

**Comment by jfernandes-dtm** [comment]
I was following the tutorial (https://yajrabox.com/docs/laravel-datatables/master/quick-starter#datatables-with-vite) and i also had this error. I think it has something to do with *bs5, but I'm lost.

**Comment by yajra** [comment]
Thanks for reporting, will review this as soon as I can. There might be new updates in the setup process and needs some fixing.

**Comment by shubhamkanchar** [comment]
Followed yajra box official document getting similar issue

**Comment by Parth86** [comment]
same error: laravel-datatables-vite.js?v=782b64a0:20230 Uncaught TypeError: Cannot read properties of undefined (reading 'defaults')
    at laravel-datatables-vite.js?v=782b64a0:20230:55......
Code where error occurs: var $6 = import_jquery5.default;
$6.extend(true, dataTables_bootstrap5_default.Buttons.defaults, {
  dom: {
    container: {
      className: "dt-buttons btn-group flex-wrap"
    },
    button: {
      className: "btn btn-secondary",
      active: "active"
    },
    collection: {
      action: {
        dropHtml: ""
      },
      container: {
        tag: "div",
        className: "dropdown-menu dt-button-collection"
      },
      closeButton: false,
      button: {
        tag: "a",
        className: "dt-button dropdown-item",
        active: "dt-button-active",
        disabled: "disabled",
        spacer: {
          className: "dropdown-divider",
          tag: "hr"
        }
      }
    },
    split: {
      action: {
        tag: "a",
        className: "btn btn-secondary dt-button-split-drop-button",
        closeButton: false
      },
      dropdown: {
        tag: "button",
        dropHtml: "",
        className: "btn btn-secondary dt-button-split-drop dropdown-toggle dropdown-toggle-split",
        closeButton: false,
        align: "split-left",
        splitAlignClass: "dt-button-split-left"
      },
      wrapper: {
        tag: "div",
        className: "dt-button-split btn-group",
        closeButton: false
      }
    }
  },
  buttonCreated: function(config, button) {
    return config.buttons ? $6('<div class="btn-group"/>').append(button) : button;
  }
});

**Comment by yajra** [comment]
Seems like an [issue](https://github.com/DataTables/Dist-DataTables-Bootstrap5/issues/10) with datatables.net-bs5. For a quick solution, try using `"datatables.net-bs5": "1.13.6"`.

**Comment by RobHowdle** [comment]
Hey! Was there any updates on this? I've had the same issue and tried using 1.13.6 but I'm still getting the same error. Unsure is this is why it's not pulling any data or just styling issues but look forward to any fixes when you have time :) Thanks!

**Comment by yajra** [comment]
There's a lot of movement in the dataTables source and v2 was just released recently. Currently working on testing/upgrading to DT v2.

I think this issue is related to v2 updates but can't trace yet where the error is coming from >.<. Fresh 1.13.10 with buttons 2.x seems to work fine last I checked.

**Comment by yajra** [comment]
I just tried to install using Laravel 11 and the script works fine. Seems like the issue was fixed on `datatables.net@1.13.11` Thanks!
